import './PolicyPage.css'

function TermsAndConditions() {
    return (
        <div className="policy-page">
            <section className="policy-hero">
                <div className="container">
                    <h1 className="policy-title">Terms & Conditions / Terms of Use</h1>

                </div>
            </section>

            <section className="policy-content">
                <div className="container">
                    {/* Centered Introduction */}
                    <div className="policy-intro text-center">
                        <p>
                            These Terms & Conditions ("Terms", "Terms of Use") govern the access to and use of the website www.eduholic.in, its subdomains, payment pages, mobile platforms, and all services offered by <strong>EDUHOLIC EDTECH INDIA PRIVATE LIMITED</strong> ("Eduholic", "Company", "We", "Us", "Our").
                        </p>
                        <p>
                            By accessing, browsing, registering, enrolling, or making any payment on the Website, you ("User", "You") agree to be legally bound by these Terms, our Privacy Policy, Refund & Return Policy, and any other policies published on the Website.
                        </p>
                    </div>

                    {/* 2-Column Grid Layout */}
                    <div className="policy-grid">

                        <div className="policy-item">
                            <h3>1. ELECTRONIC RECORD & LEGAL COMPLIANCE</h3>
                            <p>1.1 This document is an electronic record as defined under the Information Technology Act, 2000, and rules framed thereunder, including amendments relating to electronic records.</p>
                            <p>1.2 This electronic record is generated by a computer system and does not require physical or digital signatures.</p>
                            <p>1.3 This document is published in compliance with Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2011, as amended from time to time.</p>
                        </div>

                        <div className="policy-item">
                            <h3>2. COMPANY DETAILS</h3>
                            <p>The domain www.eduholic.in is owned and operated by:</p>
                            <p><strong>EDUHOLIC EDTECH INDIA PRIVATE LIMITED</strong>, a company incorporated under the Companies Act, 2013, India.</p>
                            <p>Unless repugnant to the context, "Company" shall include its directors, officers, employees, representatives, agents, affiliates, successors, and assigns.</p>
                        </div>

                        <div className="policy-item">
                            <h3>3. DEFINITIONS</h3>
                            <ul>
                                <li><strong>"Website"</strong> means www.eduholic.in and associated payment pages.</li>
                                <li><strong>"Platform"</strong> means all digital infrastructure used to deliver services.</li>
                                <li><strong>"Services"</strong> include online/offline courses, certifications, training programs, internships, events, workshops, and related offerings.</li>
                                <li><strong>"User" / "You"</strong> means any individual or legal entity competent to contract under the Indian Contract Act, 1872.</li>
                                <li><strong>"Content"</strong> includes text, videos, graphics, materials, software, and course content.</li>
                            </ul>
                        </div>

                        <div className="policy-item">
                            <h3>4. ACCEPTANCE OF TERMS</h3>
                            <p>4.1 Accessing or using the Website constitutes unconditional acceptance of these Terms.</p>
                            <p>4.2 If you do not agree to any part of these Terms, you must immediately discontinue use of the Website and Services.</p>
                            <p>4.3 These Terms apply to all users, including visitors, students, trainees, customers, contributors, and affiliates.</p>
                        </div>

                        <div className="policy-item">
                            <h3>5. MODIFICATION OF TERMS</h3>
                            <p>5.1 Eduholic reserves the right to amend, modify, or replace these Terms at any time without prior notice.</p>
                            <p>5.2 Continued use of the Website after changes constitutes acceptance of the revised Terms.</p>
                            <p>5.3 Users are responsible for periodically reviewing the Terms.</p>
                        </div>

                        <div className="policy-item">
                            <h3>6. ELIGIBILITY & ACCOUNT REGISTRATION</h3>
                            <p>6.1 Users below 18 years of age may use the Website only under the supervision and consent of a parent or legal guardian, who shall be responsible for compliance.</p>
                            <p>6.2 Certain features require account registration with accurate, current, and complete information.</p>
                            <p>6.3 Users are responsible for maintaining confidentiality of login credentials.</p>
                            <p>6.4 Eduholic reserves the right to suspend or terminate accounts for: Incorrect or misleading information, Violation of Terms, Security concerns or misuse.</p>
                        </div>

                        <div className="policy-item">
                            <h3>7. PROGRAMS, SERVICES & PRICING</h3>
                            <p>7.1 Program details, pricing, duration, and inclusions are displayed on the Website.</p>
                            <p>7.2 Prices are subject to change without notice.</p>
                            <p>7.3 Eduholic reserves the right to modify, suspend, or discontinue any Service without liability.</p>
                            <p>7.4 Course access is granted only after successful payment confirmation.</p>
                        </div>

                        <div className="policy-item">
                            <h3>8. PAYMENTS & BILLING</h3>
                            <p>8.1 Payments must be made through authorized third-party payment gateways.</p>
                            <p>8.2 Eduholic does not store credit/debit card or banking details.</p>
                            <p>8.3 By making a payment, you confirm: Legal capacity to contract, Accuracy of payment information, Authorization to use the selected payment method.</p>
                        </div>

                        <div className="policy-item">
                            <h3>9. REFUNDS, RETURNS, RESCHEDULING & COURSE CHANGES</h3>
                            <p>9.1 All refunds, cancellations, rescheduling, and course changes are governed exclusively by Eduholic's Return, Refund, Rescheduling & Course Change Policy, published separately.</p>
                            <p>9.2 Purchases made through Eduholic payment pages and www.eduholic.in are covered under the said policy.</p>
                            <p>9.3 No refunds shall be granted except as explicitly stated in the policy.</p>
                        </div>

                        <div className="policy-item">
                            <h3>10. INTELLECTUAL PROPERTY RIGHTS</h3>
                            <p>10.1 All intellectual property, including trademarks, logos, course materials, content, software, and designs, are the exclusive property of Eduholic or its licensors.</p>
                            <p>10.2 Users shall not copy, reproduce, distribute, sell, modify, or exploit any content without prior written permission.</p>
                            <p>10.3 Any infringement shall result in legal action under applicable laws.</p>
                        </div>

                        <div className="policy-item">
                            <h3>11. USER CONDUCT & OBLIGATIONS</h3>
                            <p>Users agree not to: Use the Website for unlawful purposes, Post defamatory, offensive, misleading, or illegal content, Infringe intellectual property rights, Introduce malware, viruses, or harmful code, Engage in spamming, solicitation, or unauthorized advertising, Attempt unauthorized access or security breaches.</p>
                            <p>Eduholic may remove content and terminate access without notice.</p>
                        </div>

                        <div className="policy-item">
                            <h3>12. DATA PROTECTION & PRIVACY</h3>
                            <p>12.1 Personal data is collected and processed in accordance with Eduholic's Privacy Policy and the Digital Personal Data Protection Act, 2023.</p>
                            <p>12.2 By using the Website, you consent to processing and storage of data in India.</p>
                        </div>

                        <div className="policy-item">
                            <h3>13. SECURITY</h3>
                            <p>13.1 Unauthorized access, hacking attempts, or disruption of services are strictly prohibited.</p>
                            <p>13.2 Violations may result in civil and criminal liability.</p>
                        </div>

                        <div className="policy-item">
                            <h3>14. SUSPENSION & TERMINATION</h3>
                            <p>Eduholic reserves the right to suspend or terminate access without notice if: These Terms are violated, User conduct harms the platform or other users, Required by law or regulatory authorities.</p>
                        </div>

                        <div className="policy-item">
                            <h3>15. DISCLAIMER & NO WARRANTIES</h3>
                            <p>15.1 Services are provided on an "as is" and "as available" basis.</p>
                            <p>15.2 Eduholic does not guarantee uninterrupted, error-free, or secure access.</p>
                            <p>15.3 Information provided is for general educational purposes only.</p>
                        </div>

                        <div className="policy-item">
                            <h3>16. LIMITATION OF LIABILITY</h3>
                            <p>16.1 Eduholic shall not be liable for indirect, incidental, consequential, or punitive damages.</p>
                            <p>16.2 Maximum liability, if any, shall be limited to the amount paid by the User for the specific Service.</p>
                        </div>

                        <div className="policy-item">
                            <h3>17. INDEMNITY</h3>
                            <p>Users agree to indemnify and hold harmless Eduholic from all claims arising from: Breach of these Terms, Misuse of the Website, Violation of applicable laws.</p>
                        </div>

                        <div className="policy-item">
                            <h3>18. THIRD-PARTY LINKS</h3>
                            <p>Eduholic is not responsible for third-party websites, content, or services. Accessing them is at the user's own risk.</p>
                        </div>

                        <div className="policy-item">
                            <h3>19. ELECTRONIC COMMUNICATIONS</h3>
                            <p>Users consent to receiving communications electronically. Electronic records satisfy legal requirements.</p>
                        </div>

                        <div className="policy-item">
                            <h3>20. FORCE MAJEURE</h3>
                            <p>Eduholic shall not be liable for delays or failures caused by events beyond reasonable control, including natural disasters, strikes, power failures, or government actions.</p>
                        </div>

                        <div className="policy-item">
                            <h3>21. GOVERNING LAW & JURISDICTION</h3>
                            <p>These Terms shall be governed by the laws of India.</p>
                            <p>The courts located at Hyderabad, Telangana and Andhra Pradesh shall have exclusive jurisdiction over any disputes arising out of or relating to these Terms, the Website, or the Services.</p>
                        </div>

                        <div className="policy-item">
                            <h3>22. SEVERABILITY</h3>
                            <p>If any provision is held invalid or unenforceable, the remaining provisions shall continue in full force.</p>
                        </div>

                        <div className="policy-item">
                            <h3>23. ENTIRE AGREEMENT</h3>
                            <p>These Terms, along with the Privacy Policy and other published policies, constitute the entire agreement between the User and Eduholic.</p>
                        </div>

                        <div className="policy-item">
                            <h3>24. CONTACT INFORMATION</h3>
                            <p>For any queries, grievances, or legal notices:</p>
                            <p><strong>EDUHOLIC EDTECH INDIA PRIVATE LIMITED</strong></p>
                            <p>Website: <a href="https://www.eduholic.in">https://www.eduholic.in</a></p>
                            <p>Email: <a href="mailto:support@eduholic.info">support@eduholic.info</a></p>
                        </div>

                    </div>
                </div>
            </section>
        </div>
    )
}

export default TermsAndConditions
