import './PolicyPage.css'

function TermsAndConditions() {
    return (
        <div className="policy-page">
            <div className="policy-hero">
                <div className="container">
                    <h1>Terms & Conditions</h1>
                    <p>Terms of Use</p>
                </div>
            </div>

            <div className="policy-content">
                <div className="container">
                    <section className="policy-section intro">
                        <p className="intro-text">
                            These Terms & Conditions ("Terms", "Terms of Use") govern the access to and use of the website
                            <a href="https://www.eduholic.in"> www.eduholic.in</a>, its subdomains, payment pages, mobile platforms,
                            and all services offered by <strong>EDUHOLIC EDTECH INDIA PRIVATE LIMITED</strong> ("Eduholic", "Company", "We", "Us", "Our").
                        </p>
                        <p className="agreement-notice">
                            By accessing, browsing, registering, enrolling, or making any payment on the Website, you ("User", "You")
                            agree to be legally bound by these Terms, our Privacy Policy, Refund & Return Policy, and any other policies
                            published on the Website.
                        </p>
                    </section>

                    <section className="policy-section">
                        <h2>1. Electronic Record & Legal Compliance</h2>
                        <ul>
                            <li>This document is an electronic record as defined under the Information Technology Act, 2000, and rules framed thereunder, including amendments relating to electronic records.</li>
                            <li>This electronic record is generated by a computer system and does not require physical or digital signatures.</li>
                            <li>This document is published in compliance with Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2011, as amended from time to time.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>2. Company Details</h2>
                        <p>The domain www.eduholic.in is owned and operated by:</p>
                        <div className="contact-info-box">
                            <p><strong>EDUHOLIC EDTECH INDIA PRIVATE LIMITED</strong></p>
                            <p>A company incorporated under the Companies Act, 2013, India.</p>
                        </div>
                        <p>Unless repugnant to the context, "Company" shall include its directors, officers, employees, representatives, agents, affiliates, successors, and assigns.</p>
                    </section>

                    <section className="policy-section">
                        <h2>3. Definitions</h2>
                        <ul>
                            <li><strong>"Website"</strong> means www.eduholic.in and associated payment pages.</li>
                            <li><strong>"Platform"</strong> means all digital infrastructure used to deliver services.</li>
                            <li><strong>"Services"</strong> include online/offline courses, certifications, training programs, internships, events, workshops, and related offerings.</li>
                            <li><strong>"User" / "You"</strong> means any individual or legal entity competent to contract under the Indian Contract Act, 1872.</li>
                            <li><strong>"Content"</strong> includes text, videos, graphics, materials, software, and course content.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>4. Acceptance of Terms</h2>
                        <ul>
                            <li>Accessing or using the Website constitutes unconditional acceptance of these Terms.</li>
                            <li>If you do not agree to any part of these Terms, you must immediately discontinue use of the Website and Services.</li>
                            <li>These Terms apply to all users, including visitors, students, trainees, customers, contributors, and affiliates.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>5. Modification of Terms</h2>
                        <ul>
                            <li>Eduholic reserves the right to amend, modify, or replace these Terms at any time without prior notice.</li>
                            <li>Continued use of the Website after changes constitutes acceptance of the revised Terms.</li>
                            <li>Users are responsible for periodically reviewing the Terms.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>6. Eligibility & Account Registration</h2>
                        <ul>
                            <li>Users below 18 years of age may use the Website only under the supervision and consent of a parent or legal guardian, who shall be responsible for compliance.</li>
                            <li>Certain features require account registration with accurate, current, and complete information.</li>
                            <li>Users are responsible for maintaining confidentiality of login credentials.</li>
                            <li>Eduholic reserves the right to suspend or terminate accounts for incorrect or misleading information, violation of Terms, security concerns or misuse.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>7. Courses, Services & Pricing</h2>
                        <ul>
                            <li>Course details, pricing, duration, and inclusions are displayed on the Website.</li>
                            <li>Prices are subject to change without notice.</li>
                            <li>Eduholic reserves the right to modify, suspend, or discontinue any Service without liability.</li>
                            <li>Course access is granted only after successful payment confirmation.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>8. Payments & Billing</h2>
                        <ul>
                            <li>Payments must be made through authorized third-party payment gateways.</li>
                            <li>Eduholic does not store credit/debit card or banking details.</li>
                            <li>By making a payment, you confirm legal capacity to contract, accuracy of payment information, and authorization to use the selected payment method.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>9. Refunds, Returns, Rescheduling & Course Changes</h2>
                        <ul>
                            <li>All refunds, cancellations, rescheduling, and course changes are governed exclusively by Eduholic's Return, Refund, Rescheduling & Course Change Policy, published separately.</li>
                            <li>Purchases made through Eduholic payment pages and www.eduholic.in are covered under the said policy.</li>
                            <li>No refunds shall be granted except as explicitly stated in the policy.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>10. Intellectual Property Rights</h2>
                        <ul>
                            <li>All intellectual property, including trademarks, logos, course materials, content, software, and designs, are the exclusive property of Eduholic or its licensors.</li>
                            <li>Users shall not copy, reproduce, distribute, sell, modify, or exploit any content without prior written permission.</li>
                            <li>Any infringement shall result in legal action under applicable laws.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>11. User Conduct & Obligations</h2>
                        <p>Users agree not to:</p>
                        <ul>
                            <li>Use the Website for unlawful purposes</li>
                            <li>Post defamatory, offensive, misleading, or illegal content</li>
                            <li>Infringe intellectual property rights</li>
                            <li>Introduce malware, viruses, or harmful code</li>
                            <li>Engage in spamming, solicitation, or unauthorized advertising</li>
                            <li>Attempt unauthorized access or security breaches</li>
                        </ul>
                        <p>Eduholic may remove content and terminate access without notice.</p>
                    </section>

                    <section className="policy-section">
                        <h2>12. Data Protection & Privacy</h2>
                        <ul>
                            <li>Personal data is collected and processed in accordance with Eduholic's Privacy Policy and the Digital Personal Data Protection Act, 2023.</li>
                            <li>By using the Website, you consent to processing and storage of data in India.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>13. Security</h2>
                        <ul>
                            <li>Unauthorized access, hacking attempts, or disruption of services are strictly prohibited.</li>
                            <li>Violations may result in civil and criminal liability.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>14. Suspension & Termination</h2>
                        <p>Eduholic reserves the right to suspend or terminate access without notice if:</p>
                        <ul>
                            <li>These Terms are violated</li>
                            <li>User conduct harms the platform or other users</li>
                            <li>Required by law or regulatory authorities</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>15. Disclaimer & No Warranties</h2>
                        <ul>
                            <li>Services are provided on an "as is" and "as available" basis.</li>
                            <li>Eduholic does not guarantee uninterrupted, error-free, or secure access.</li>
                            <li>Information provided is for general educational purposes only.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>16. Limitation of Liability</h2>
                        <ul>
                            <li>Eduholic shall not be liable for indirect, incidental, consequential, or punitive damages.</li>
                            <li>Maximum liability, if any, shall be limited to the amount paid by the User for the specific Service.</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>17. Indemnity</h2>
                        <p>Users agree to indemnify and hold harmless Eduholic from all claims arising from:</p>
                        <ul>
                            <li>Breach of these Terms</li>
                            <li>Misuse of the Website</li>
                            <li>Violation of applicable laws</li>
                        </ul>
                    </section>

                    <section className="policy-section">
                        <h2>18. Third-Party Links</h2>
                        <p>Eduholic is not responsible for third-party websites, content, or services. Accessing them is at the user's own risk.</p>
                    </section>

                    <section className="policy-section">
                        <h2>19. Electronic Communications</h2>
                        <p>Users consent to receiving communications electronically. Electronic records satisfy legal requirements.</p>
                    </section>

                    <section className="policy-section">
                        <h2>20. Force Majeure</h2>
                        <p>Eduholic shall not be liable for delays or failures caused by events beyond reasonable control, including natural disasters, strikes, power failures, or government actions.</p>
                    </section>

                    <section className="policy-section">
                        <h2>21. Governing Law & Jurisdiction</h2>
                        <p>These Terms shall be governed by the laws of India.</p>
                        <p>The courts located at <strong>Hyderabad, Telangana and Andhra Pradesh</strong> shall have exclusive jurisdiction over any disputes arising out of or relating to these Terms, the Website, or the Services.</p>
                    </section>

                    <section className="policy-section">
                        <h2>22. Severability</h2>
                        <p>If any provision is held invalid or unenforceable, the remaining provisions shall continue in full force.</p>
                    </section>

                    <section className="policy-section">
                        <h2>23. Entire Agreement</h2>
                        <p>These Terms, along with the Privacy Policy and other published policies, constitute the entire agreement between the User and Eduholic.</p>
                    </section>

                    <section className="policy-section">
                        <h2>24. Contact Information</h2>
                        <p>For any queries, grievances, or legal notices:</p>
                        <div className="contact-info-box">
                            <p><strong>EDUHOLIC EDTECH INDIA PRIVATE LIMITED</strong></p>
                            <p><strong>Website:</strong> <a href="https://www.eduholic.in">https://www.eduholic.in</a></p>
                            <p><strong>Email:</strong> <a href="mailto:support@eduholic.info">support@eduholic.info</a></p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    )
}

export default TermsAndConditions
